---

- hosts: localhost

  tasks:

  - name: Install ansible from github
    git:
      repo: https://github.com/ansible/ansible.git
      dest: ~/ansible

  - name: Install dev ansible
    pip:
      requirements: /home/db0/ansible/requirements.txt
  
  - name: create python -> python3 symlink
    file:
      src: /usr/bin/python3
      dest: /usr/bin/python
      state: link
    become: true
    ignore_errors: true
 
  - name: Install other useful packages
    dnf:
      name: 
      - bat
      - exa
      - htop
      - ack
      - task
      - tldr
      - screen
      - vim
      - prettyping
      state: latest
    become: true


  - name: setup some expected dirs
    file:
      dest: "{{ item }}"
      state: directory
    loop:
    - "~/.privIncludes/"
    - "~/git/"

  - name: setup my workstation setup repo
    git:
      repo: https://github.com/db0/workstation_setup.git
      dest: ~/git/workstation_setup
      update: no # We just need to make sure it's there

  - name: setup .bash_profile
    file:
      src: ~/git/workstation_setup/.bash_profile
      dest: ~/.bash_profile
      state: link
      force: true

  - name: setup .bashIncludes
    file:
      src: ~/git/workstation_setup/.bashIncludes
      dest: ~/.bashIncludes
      state: link

  - name: setup scripts dir
    file:
      src: ~/git/workstation_setup/scripts
      dest: ~/scripts
      state: link

  - name: delete .bashrc if it exists
    file:
      dest: ~/.bashrc
      state: absent

  - name: setup basic vars in new .bashrc
    lineinfile:
      path: ~/.bashrc
      line: "{{ item }}"
      create: true
    loop:
    - "export SCRIPTS=~/scripts"
    - "export PRIV_DESKTOP={{ansible_hostname}}"
    - "export SERV_ACC={{ansible_user_id}} # Change this to the account you use to login to other hosts if your not your local username (e.g. root)"
    - "source ~/ansible/hacking/env-setup -q"
    - "shopt -q login_shell || source ~/.bash_profile" # We don't want to end up in an infinite loop
    - "[[ -r ~/.bash_completion ]] && source ~/.bash_completion # If you have a bash_completion source, put it here"

  - name: Remove standard ansible now that we have devel
    dnf:
      name: ansible
      state: absent
    become: true

